doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        # Configura la versión de tu servidor de base de datos si es necesario
        # server_version: '16'
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        server_version: '8.0.41'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                type: attribute  
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            # En caso de estar en entorno de pruebas, puedes configurar el nombre de la base de datos
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system

    migrations:
        migrations_paths:
            'App\Migrations': '%kernel.project_dir%/migrations'
