# config/packages/security.yaml

security:
    # Codificadores de contrase침as
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    # Proveedores de usuarios
    providers:
        database_users:
            entity:
                class: App\Entity\User
                property: username

    # Firewalls (Protecci칩n de rutas de la API)
    firewalls:
        api:
            pattern: ^/api/
            stateless: true # No usamos sesiones, todo es sin estado
            http_basic: ~ # Autenticaci칩n b치sica para las rutas API

    # Control de acceso
    access_control:
        - { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/, roles: ROLE_USER }
